---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Risk Audit API"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: Risk Audit
    description: Everything about AFCII Risk Audit

paths:
  /findAllUsers:
    get:
      tags:
        - users
      description: "Returns all users"
      operationId: "findAllUsers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "A list of users."
          schema:
            $ref: "#/definitions/GetUsersDto"
        "500":
          description: "Response with error."
          schema:
            $ref: "#/definitions/ErrorResponse"

  /createUser:
    post:
      tags:
        - users
      description: "Create a user"
      operationId: "createUser"
      parameters:
        - in: body
          name: userDTO
          description: "User save"
          schema:
            $ref: '#/definitions/CreateUserDto'
      responses:
        "201":
          description: "A user created."
          schema:
            $ref: "#/definitions/GetUserDto"
        "500":
          description: "Response with error."
          schema:
            $ref: "#/definitions/ErrorResponse"


  /findUserById/{userId}:
    get:
      tags:
        - users
      description: "Returns user by id"
      operationId: "findUserById"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          required: true
          type: "integer"
          format: "int64"
          minimum: 1
          description: "get user by id"
      responses:
        "200":
          description: "A users"
          schema:
            $ref: "#/definitions/GetUserDto"
        "500":
          description: "Response with error."
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  GetUsersDto:
    type: "array"
    items:
      $ref: "#/definitions/GetUserDto"
  GetUserDto:
    type: "object"
    required:
      - "id"
      - "username"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
  CreateUserDto:
    type: "object"
    required:
      - "username"
      - "email"
      - "password"
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"

  ErrorResponse:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
