codeGen:
  rickAndMorty: https://rickandmortyapi.com/api

spring:
  h2:
    console:
      enabled: true
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:h2:mem:test
  driverClassName: org.h2.Driver
  username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10