codeGen:
  rickAndMorty: https://rickandmortyapi.com/api

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #show-sql: true

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterHours: 1
    refreshTokenExpirationAfterHours: 2